spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kookminfeed}
    username: ${DB_USERNAME:kookmin}
    password: ${DB_PASSWORD:kookmin1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

server:
  port: 8080
