spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kookminfeed}
    username: ${DB_USERNAME:kookmin}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

server:
  port: 8080
